version: '2'
services:
    inventory-app:
        image: inventory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://inventory-mysql:3306/inventory?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=inventory-elasticsearch:9300
        ports:
            - 8080:8080
    inventory-mysql:
        extends:
            file: mysql.yml
            service: inventory-mysql
    inventory-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: inventory-elasticsearch
